import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';
import './plugins/bootstrap/css/bootstrap.min.css';
import './plugins/bootstrap-select/css/bootstrap-select.css';
import './plugins/node-waves/waves.css';
import './assets/css/style.css';
import './assets/css/filmList.css';
ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
